Add electron-22-0.md
electronjs-cn/blog pull request #7
Opened 2022-12-05 12:55 UTC by Cyberhan123

2022-12-05 13:01 UTC, BlackHole1 requested changes
/cc @electronjs-cn/translation

2022-12-05 13:01 UTC, BlackHole1 commented on electron-22-0.md
> +如果您有任何反馈，请在Twitter上与我们分享，或加入我们的社区 [Discord](https://discord.com/invite/electronjs)！ Bug 和功能请求可以在 Electron 的 [问题跟踪器](https://github.com/electron/electron/issues) 中报告。
```suggestion
如果您有任何反馈，请在 Twitter 上与我们分享，或加入我们的社区 [Discord](https://discord.com/invite/electronjs)！ Bug 和功能请求可以在 Electron 的 [问题跟踪器](https://github.com/electron/electron/issues) 中报告。
```

2022-12-05 13:01 UTC, BlackHole1 commented on electron-22-0.md
> +该API是基于Node.js的 `child_process.fork` 设计的，以允许更容易的过渡，一个主要的区别是，入口点 `modulePath` 必须来自打包的应用程序内，以允许只加载受信任的脚本。
```suggestion
该 API 是基于 Node.js 的 `child_process.fork` 设计的，以允许更容易的过渡，一个主要的区别是，入口点 `modulePath` 必须来自打包的应用程序内，以允许只加载受信任的脚本。 
```

2022-12-06 02:30 UTC, LitoMore approved these changes

2022-12-06 02:38 UTC, merged