docs: add electron 23
electronjs-cn/blog pull request #8
Opened 2023-02-09 12:23 UTC by sriting

2023-02-09 12:33 UTC, BlackHole1 requested changes

2023-02-09 12:33 UTC, BlackHole1 commented on blog/electron-23-0.md
> +Electron 23.0.0 已发布！ 此次升级中包含 Chromium `110`, V8 `11.0`, 和 Node.js `18.12.1`。  此外，取消了对Windows 7/8.1的支持。 请阅读下文了解更多详情！
```suggestion
Electron 23.0.0 已发布！ 此次升级中包含 Chromium `110`, V8 `11.0`, 和 Node.js `18.12.1`。  此外，取消了对 Windows 7/8.1 的支持。 请阅读下文了解更多详情！
```

2023-02-09 12:33 UTC, BlackHole1 commented on blog/electron-23-0.md
> +如果您有任何反馈，请在Twitter上与我们分享，或加入我们的社区 [Discord](https://discord.com/invite/electronjs)！ Bug 和功能请求可以在 Electron 的 [问题跟踪器](https://github.com/electron/electron/issues) 中报告。
```suggestion
如果您有任何反馈，请在 Twitter 上与我们分享，或加入我们的社区 [Discord](https://discord.com/invite/electronjs)！ Bug 和功能请求可以在 Electron 的 [问题跟踪器](https://github.com/electron/electron/issues) 中报告。
```

2023-02-09 12:33 UTC, BlackHole1 commented on blog/electron-23-0.md
> +    * [Chromium有新版本109](https://developer.chrome.com/blog/new-in-chrome-109/)
```suggestion
    * [Chromium 有新版本110](https://developer.chrome.com/blog/new-in-chrome-110/)
    * [Chromium 有新版本109](https://developer.chrome.com/blog/new-in-chrome-109/)
```

2023-02-09 12:33 UTC, BlackHole1 commented on blog/electron-23-0.md
> +Electron 23 不再支持Windows 7/8.1。 Electron 遵循计划中的 Chromium 弃用政策，该政策将 [在 Chromium 109 中弃用 Windows 7/8/8.1 支持（在此处阅读更多信息）](https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-
```suggestion
Electron 23 不再支持 Windows 7/8.1。 Electron 遵循计划中的 Chromium 弃用政策，该政策将 [在 Chromium 109 中弃用 Windows 7/8/8.1 支持（在此处阅读更多信息）](https://support.google.com/chrome/thread/185534985/sunsetting-support-for-windows-7-8-8-1-in-early-2023?hl=en)。
```

2023-02-09 12:33 UTC, BlackHole1 commented on blog/electron-23-0.md
> +根据项目的[支持政策](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#version-support-policy)，Electron 20.x.y 已经达到了支持的终点。 Developers and applications are encouraged to upgrade to a newer ver
"Developers and applications are encouraged to upgrade to a newer version of Electron."

没有翻译

2023-02-09 13:09 UTC, Cyberhan123 approved these changes

2023-02-11 05:27 UTC, BlackHole1 approved these changes

2023-02-11 05:28 UTC, merged